import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import Header from "./components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const router = useRouter();
  
  return (
    <ClerkProvider
      appearance={{
        variables: { colorPrimary: '#624CF5' },
        
      }}
    >
      <html lang="en">
        <body className={`${inter.className}`}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
